ZTX.lang = {
    'pl': {
        'start': 'Start',
        'settings': 'Ustawienia',
        'restoreSettings': 'Przywróc ustawienia domyślne',
        'animationGroup': 'Animacja',
        'zoomGroup': 'Zoom',
        'respGroup': 'Odrodzenie',
        'namesGroup': 'Nazwy',
        'massGroup': 'Masa',
        'skinsGroup': 'Skiny',
        'foodGroup': 'Pokarm',
        'transparencyGroup': 'Przezroczystość / kolory',
        'gridGroup': 'Siatka / sektory',
        'miniMapGroup': 'Minimapa',
        'helpersGroup': 'Wspomagacze',
        'mouseGroup': 'Sterowanie myszką',
        'hudGroup': 'HUD',
        'chatGroup': 'Czat',
        'statsGroup': 'Statystyki',
        'extrasGroup': 'Dodatkowe',
        'noSkins': 'Wyłącz skiny',
        'noNames': 'Wyłącz nazwy',
        'noColors': 'Wyłącz kolory',
        'showMass': 'Pokaż masę',
        'skipStats': 'Pomiń statystyki po śmierci',
        'showQuest': 'Pokaż zadanie (quest)',
        'autoZoom': 'Auto zoom',
        'animation': 'Opóźnienie animacji',
        'suckAnimation': 'Cell Eat [Sucking] Animation',
        'virusGlow': 'Virus Glow',
        'borderGlow': 'Border Glow',
        'zoomSpeedValue2': 'Szybkość zoomu',
        'quickResp': 'Szybkie odrodzenie (klawisz)',
        'autoResp': 'Auto odrodzenie',
        'autoHideCellsInfo': 'Autoukrywanie nazw i masy',
        'autoHideNames': 'Autoukrywanie nazw',
        'autoHideMass': 'Autoukrywanie masy',
        'autoHideFood': 'Autoukrywanie pokarmu - masa',
        'autoHideFoodOnZoom': 'Autoukrywanie pokarmu - zoom',
        'optimizedNames': 'Zoptymalizowane nazwy',
        'hideMyName': 'Ukryj własną nazwę',
        'hideTeammatesNames': 'Ukryj nazwy graczy teamu',
        'optimizedMass': 'Optimized mass (+/-2%) & Merge timer BETA off\n Suggested to be enabled for Lag reduce',
        'shortMass': 'Skrócona masa (k)',
        'virMassShots': 'Licznik strzałów (wirusy)',
        'hideMyMass': 'Ukryj własną masę',
        'hideEnemiesMass': 'Ukryj masę przeciwników',
        'vanillaSkins': 'Podstawowe skiny',
        'customSkins': 'Własne skiny',
        'videoSkins': 'Video skins (.mp4 .webm .ogv)',
        'videoSkinsMusic': 'Sound from other\'s Video skins when both C3',
        'myTransparentSkin': 'Mój przezroczysty skin',
        'myCustomColor': 'Mój własny kolor',
        'transparentCells': 'Przezroczyste kulki',
        'transparentViruses': 'Przezroczyste wirusy',
        'transparentSkins': 'Przezroczyste skiny',
        'showGrid': 'Siatka',
        'showBgSectors': 'Sektory w tle',
        'showMapBorders': 'Granice mapy',
        'showGhostCells': 'Duchy kulek (fps drop)',
        'showGhostCellsInfo': 'Ghost cells info (confusing)',
        'showMiniMap': 'Pokaż minimapę',
        'showMiniMapGrid': 'Pokaż siatkę minimapy',
        'showMiniMapGuides': 'Pokaż prowadnice na minimapie',
        'showExtraMiniMapGuides': 'Show extra minimap guides',
        'showMiniMapGhostCells': 'Pokaż duchy kulek na minimapie',
        'oneColoredTeammates': 'Jednokolorowi gracze',
        'optimizedFood': 'Zoptymalizowany pokarm',
        'rainbowFood': 'Kolorowy pokarm',
        'oppColors': 'Kolory przeciwników',
        'oppRings': 'Ringi przeciwników',
        'virColors': 'Kolory wirusów',
        'splitRange': 'Zasięg podziału',
        'virusesRange': 'Zasięg wirusów',
        'textStroke': 'Obwódki nazw i masy',
        'namesStroke': 'Obwódki nazw',
        'massStroke': 'Obwódki masy',
        'cursorTracking': 'Śledzenie kursora',
        'teammatesInd': 'Wskaźniki graczy teamu',
        'mouseSplit': 'LPM - Split myszką',
        'mouseFeed': 'PPM - Feed myszką',
        'mouseInvert': 'Odwróć klawisze myszki',
        'disableChat': 'Wyłącz czat',
        'hideChat': 'Ukryj czat',
        'chatSounds': 'Powiadomienia dźwiękowe',
        'chatEmoticons': 'Emotikony',
        'showChatImages': 'Pokaż obrazki na czacie',
        'showChatVideos': 'Pokaż filmiki na czacie',
        'showChatBox': 'Czatbox zamiast wyskakujących wiadomości',
        'messageSound': 'Dźwięk powiadomienia o wiadomości',
        'commandSound': 'Dźwięk powiadomienia o komendzie',
        'virusSoundurl': 'Virus shot sound',
        'virusSound': 'Virus shot sound',
        'jellyPhisycs': 'Jelly physics',
        'showTop5': 'Pokaż top 5 teamu',
        'showTargeting': 'Pokaż namierzanie',
        'showTime': 'Pokaż aktualny czas',
        'showLbData': 'Pokaż masę w topce',
        'normalLb': 'Nagłówek \"Topka\"',
        'centeredLb': 'Wyśrodkowana topka',
        'fpsAtTop': 'Statystyki na górze',
        'showStats': 'Pokaż statystyki',
        'showStatsMass': 'Statystyki: Masa',
        'showStatsSTE': 'Statystyki: Przedziały Masy',
        'showStatsESTE': 'Statystyki: STE wroga',
        'showStatsEMTE': 'Statystyki: MTE wroga',
        'showStatsMTE': 'Statystyki: Nasze MTE',
        'showStatsSTE': 'Statystyki: Nasze STE',
        'showStatsTTE': 'Statystyki: Minimalna masa mate\'a do tricksplitu',
        'showStatsPTE': 'Statystyki: Maksymalna masa wroga do presplitu',
        'showStatsN16': 'Statystyki: n/16',
        'showStatsFPS': 'Statystyki: FPS',
        'blockPopups': 'Blokuj popupy (reklamy/sklep/zadanie)',
        'hotkeys': 'Skróty klawiszowe',
        'hk-inst-assign': 'Aby ustawić skrót klawiszowy kliknij na polu skrótu i naciśnij wybrany klawisz.',
        'hk-inst-delete': 'Aby usunąć skrót klawiszowy kliknij na polu skrótu i naciśnij klawisz DELETE.',
        'hk-inst-keys': 'Możliwe kombinacje skrótów klawiszowych z użyciem klawiszy CTRL oraz ALT.',
        'hk-bots-split': 'Bots split',
        'hk-bots-feed': 'Bots feed',
        'hk-bots-ai': 'Bots AI toggle',
        'hk-feed': 'Feed',
        'hk-macroFeed': 'Szybki feed',
        'hk-split': 'Podział',
        'hk-doubleSplit': 'Podwójny podział',
        'hk-split16': 'Podział na 16',
        'hk-pause': 'Pauza kulki',
        'hk-showTop5': 'Pokaż/ukryj top 5 teamu',
        'hk-showTime': 'Pokaż/ukryj aktualny czas',
        'hk-showSplitRange': 'Pokaż/ukryj zasięg podziału',
        'hk-showSplitInd': 'Pokaż/ukryj zasięg podziału z ringami',
        'hk-showTeammatesInd': 'Pokaż/ukryj wskaźniki graczy teamu',
        'hk-showOppColors': 'Pokaż/ukryj kolory przeciwników',
        'hk-toggleSkins': 'Przełącz skiny (własne/standardowe)',
        'hk-showSkins': 'Pokaż/ukryj skiny',
        'hk-transparentSkins': 'Włącz/wyłącz przezroczyste skiny',
        'hk-showStats': 'Pokaż/ukryj statystyki gry',
        'hk-toggleCells': 'Przełącz kulkę (najmniejsza/największa)',
        'hk-showFood': 'Pokaż/ukryj pokarm',
        'hk-showGrid': 'Pokaż/ukryj siatkę',
        'hk-showMiniMapGuides': 'Pokaż/ukryj prowadnice na minimapie',
        'hk-hideChat': 'Pokaż/ukryj czat',
        'hk-showHUD': 'Pokaż/ukryj HUD',
        'hk-copyLb': 'Kopiuj topkę',
        'hk-showLb': 'Pokaż/ukryj topkę',
        'hk-toggleAutoZoom': 'Włącz/wyłącz auto zoom',
        'hk-resetZoom': 'Reset zoomu',
        'hk-zoomLevel': 'Zoom - poziom',
        'hk-toggleDeath': 'Przełącz miejsce śmierci',
        'hk-clearChat': 'Pokaż historię czatu / Czyść czat',
        'hk-showBgSectors': 'Pokaż/ukryj sektory w tle',
        'hk-hideBots': 'Pokaż/ukryj małe boty',
        'hk-showNames': 'Pokaż/ukryj nazwy',
        'hk-hideTeammatesNames': 'Pokaż/ukryj nazwy graczy teamu',
        'hk-showMass': 'Pokaż/ukryj masę',
        'hk-showMiniMap': 'Pokaż/ukryj minimapę',
        'hk-chatMessage': 'Napisz wiadomość na czacie',
        'hk-quickResp': 'Szybkie odrodzenie (respawn)',
        'hk-autoResp': 'Włącz/wyłacz auto odrodzenie',
        'hk-switchServerMode': 'Przełącz serwer [publiczny/prywatny]',
        'hk-showTargeting': 'Pokaż/ukryj panel namierzania',
        'hk-voiceChat': 'Głos do tekstu',
        'hk-GhostCellsInfo': 'Show ghost cells information',
        'hk-Autoplay': 'Auto Play',
        'hk-setTargeting': 'Włącz/wyłącz namierzanie (śledzenie)',
        'hk-cancelTargeting': 'Zatrzymaj namierzanie',
        'hk-changeTarget': 'Zmień cel',
        'hk-privateMiniMap': 'Pokaż cel na minimapie',
        'hk-showQuest': 'Pokaż/ukryj zadanie',
        'commands': 'Komendy',
        'comm1': 'Feeduj!',
        'comm2': 'Dziel się!',
        'comm3': 'Pomocy na %currentSector%!',
        'comm4': 'Wróg na %currentSector%!',
        'comm5': 'Zabij pomocnika!',
        'comm6': 'Strzel z wirusa!',
        'comm7': 'Zjedz wirusa!',
        'comm8': 'Zjebałem, wybacz.',
        'comm9': 'Ja pierdolę...',
        'comm0': 'Kurwa mać!',
        'comm10': 'Trick!',
        'comm11': 'Lewo!',
        'comm12': 'Góra!',
        'comm13': 'Prawo!',
        'comm14': 'Dół!',
        'comm15': 'Fake Tricksplit',
        'comm16': 'Popsplit',
        'comm17': 'Double Popsplit',
        'comm18': 'Reversed Tricksplit',
        'comm19': 'Canonsplit',
        'comm20': 'Reversed Canonsplit',
        'comm21': 'Bowlingsplit',
        'comm22': 'Auto feed trick',
        'comm23': 'Pause',
        'comm24': 'ANTI alarm stage 1',
        'comm25': 'ANTI alarm stage 2',
        'comm26': 'ANTI alarm stage 3',
        'comm27': 'ANTI alarm stage 4',
        'comm28': 'ANTI alarm stage 5',
        'comm29': 'Presplit',
        'comm30': 'Party Run tricks',
        'saveComm': 'Zapisz komendy',
        'theme': 'Wygląd',
        'restoreThemeSettings': 'Przywróc ustawienia domyślne wyglądu',
        'basicTheming': 'Podstawowy',
        'themePreset': 'Motyw',
        'themeType': 'Typ motywu',
        'darkTheme': 'Ciemny motyw',
        'lightTheme': 'Jasny motyw',
        'mainColor': 'Kolor główny',
        'bgColor': 'Tło',
        'bordersColor': 'Granice mapy',
        'gridColor': 'Siatka',
        'sectorsColor': 'Czcionka sektorów',
        'namesColor': 'Nazwy',
        'namesStrokeColor': 'Obwódki nazw',
        'massColor': 'Masa',
        'massStrokeColor': 'Obwódki masy',
        'virusColor': 'Wirusy',
        'virusStrokeColor': 'Obwódki wirusów',
        'virusGlowColor': "Virus Glow",
        "borderGlowColor": "Border Glow",
        'mVirusColor': 'Mothercell',
        'mVirusStrokeColor': 'Mothercell stroke',
        'virusGlowSize': 'Virus Glow Size',
        'borderGlowSize': 'Border Glow Size',
        'foodColor': 'Pokarm',
        'namesFont': 'Czcionka nazw',
        'massFont': 'Czcionka masy',
        'sectorsFont': 'Czcionka sektorów',
        'namesScale': 'Skala nazw',
        'massScale': 'Skala masy',
        'virMassScale': 'Skala masy wirusów',
        'strokeScale': 'Skala obwódek tekstu',
        'foodSize': 'Wielkość pokarmu',
        'bordersWidth': 'Grubość granic mapy',
        'sectorsWidth': 'Grubość siatki sektorów',
        'sectorsFontSize': 'Rozmiar czcionki sektorów',
        'cellsAlpha': 'Przezroczystość kulek',
        'skinsAlpha': 'Przezroczystość skinów',
        'virusAlpha': 'Przezroczystość wirusów',
        'textAlpha': 'Przezroczystość nazw i masy',
        'virusStrokeSize': 'Grubość obwódki wirusów',
        "virusGlowSize": "Virus Glow Size",
        'teammatesIndColor': 'Wskaźnik gracza',
        'cursorTrackingColor': 'Śledzenie kursora',
        'splitRangeColor': 'Zasięg podziału',
        'qdsplitRange': 'Zasięg szybkiego podwójnego podziału', //Sonia2
        'sdsplitRange': 'Zasięg powolnego podwójnego podziału', //Sonia2
        'enemyBSTEDColor': 'Kolor W2STE wroga', //Sonia2
        'enemyBSTEColor': 'Kolor WSTE wroga', //Sonia2
        'enemyBColor': 'Kolor większego wroga', //Sonia2
        'enemySColor': 'Kolor mniejszego wroga', //Sonia2
        'enemySSTEColor': 'Kolor MSTE wroga', //Sonia2
        'enemySSTEDColor': 'Kolor M2STE wroga', //Sonia2
        'safeAreaColor': 'Bezpieczna strefa',
        'dangerAreaColor': 'Strefa zagrożenia',
        'ghostCellsColor': 'Duchy kulek',
        'ghostCellsAlpha': 'Przezroczystość duchów kulek',
        'menuTheming': 'Menu',
        'menuPreset': 'Motyw menu',
        'menuMainColor': 'Kolor główny',
        'menuBtnTextColor': 'Tekst przycisku',
        'menuPanelColor': 'Panel',
        'menuPanelColor2': 'Panel (2)',
        'menuTextColor': 'Tekst panelu',
        'menuTextColor2': 'Tekst panelu (2)',
        'btn1Color': 'Przycisk #1',
        'btn1Color2': 'Przycisk #1 (2)',
        'btn2Color': 'Przycisk #2',
        'btn2Color2': 'Przycisk #2 (2)',
        'btn3Color': 'Przycisk #3',
        'btn3Color2': 'Przycisk #3 (2)',
        'btn4Color': 'Przycisk #4',
        'btn4Color2': 'Przycisk #4 (2)',
        'menuBg': 'Grafika tła panelu',
        'menuOpacity': 'Przezroczystość',
        'hudTheming': 'HUD',
        'hudMainColor': 'Kolor główny',
        'hudColor': 'Tło',
        'hudTextColor': 'Tekst',
        'statsHudColor': 'Statystyki',
        'timeHudColor': 'Czas',
        'top5MassColor': 'Masa',
        'lbMeColor': 'Topka - ja',
        'lbTeammateColor': 'Topka - team',
        'hudFont': 'Czcionka HUD',
        'hudScale': 'Skala HUD',
        'chatTheming': 'Czat',
        'messageColor': 'Tło wiadomości',
        'messageTextColor': 'Tekst wiadomości',
        'messageTimeColor': 'Czas wiadomości',
        'messageNickColor': 'Nick wiadomości',
        'commandsColor': 'Tło komendy',
        'commandsTextColor': 'Tekst komendy',
        'commandsTimeColor': 'Czas komendy',
        'commandsNickColor': 'Nick komendy',
        'chatBoxColor': 'Tło czatboxu',
        'chatScale': 'Skala czatu',
        'miniMapTheming': 'Minimapa',
        'miniMapSectorsColor': 'Sektory',
        'miniMapSectorColor': 'Aktualny sektor',
        'miniMapGuidesColor': 'Prowadnice',
        'miniMapNickColor': 'Nick',
        'miniMapNickStrokeColor': 'Obwódka nicku',
        'miniMapMyCellColor': 'Moja kulka',
        'miniMapMyCellStrokeColor': 'Obwódka mojej kulki',
        'miniMapTeammatesColor': 'Gracze',
        'miniMapDeathLocationColor': 'Miejsce śmierci',
        'miniMapFont': 'Czcionka minimapy',
        'miniMapNickFont': 'Czcionka nicku',
        'miniMapWidth': 'Szerokość minimapy',
        'miniMapSectorsOpacity': 'Przezroczystość sektorów',
        'miniMapNickSize': 'Rozmiar nicku',
        'miniMapNickStrokeSize': 'Grubość obwódki nicku',
        'miniMapMyCellSize': 'Wielkość mojej kulki',
        'miniMapMyCellStrokeSize': 'Grubość obwódki mojej kulki',
        'miniMapTeammatesSize': 'Wielkość graczy',
        'miniMapGhostCellsColor': 'Duchy kulek',
        'miniMapGhostCellsAlpha': 'Przezroczystość duchów kulek',
        'imagesTheming': 'Grafika / kursory',
        'customBackground': 'Grafika tła',
        'customCursor': 'Grafika kursora',
        'hideChatMsgA': 'Czat został włączony!',
        'hideChatMsgB': 'Czat został ukryty!',
        'showSkinsMsgA': 'Skiny zostały włączone!',
        'showSkinsMsgB': 'Skiny zostały ukryte!',
        'hideSmallBotsMsgA': 'Małe boty stały się widoczne!',
        'hideSmallBotsMsgB': 'Małe boty zostały ukryte!',
        'autoRespMsgA': 'Auto odrodzenie zostało włączone!',
        'autoRespMsgB': 'Auto odrodzenie zostało wyłączone!',
        'autoZoomMsgA': 'Auto zoom został włączony!',
        'autoZoomMsgB': 'Auto zoom został wyłączony!',
        //                   'targetNotSet': 'Brak celu',
        'targetNotSet': '',
        'targetDead': 'Nie żyje',
        'targetDistance': 'Dystans',
        'targetMass': 'Masa razem',
        'totalPartyPlayers': '',
        'totalPartyMass': '',
        'exportImport': 'Eksport / import ustawień',
        'exportSettings': 'Eksportuj ustawienia',
        'exportInfo': 'Aby wyeksportować wybrane ustawienia skopiuj poniższy kod i zapisz go w pliku tekstowym z kodowaniem Unicode.',
        'importSettings': 'Importuj ustawienia',
        'importInfo': 'Aby zaimportować wybrane ustawienia wklej poniżej wyeksportowany wcześniej kod i naciśnij przycisk \"Importuj ustawienia\".',
        'profile': 'Profil',
        'profiles': 'Profile',
        'skins': 'Skiny',
        'moreSkins': 'Dodaj skiny',
        'thanks': 'Dzięki Awesome!',
        'saveSett': 'Zapisz ustawienia',
        'saved': 'Zapisano!',
        'resetSett': 'Resetuj ustawienia',
        'close': 'Zamknij',
        'enterChatMsg': 'Napisz wiadomość',
        'activeParties': 'Aktywne party',
        'noActiveParties': 'Brak aktywnych party ;(',
        'playlist': 'Playlista',
        'pause': 'PAUZA!',
        'visit': 'Odwiedź',
        'exit': 'Legend mod Express: Czy na pewno chcesz opuścic grę?',
        'blockWarn': 'UWAGA! Popupy zostały zablokowane w ustawieniach.',
        'unblockPopups': 'Odblokuj tymczasowo',
        'mass': 'Masa',
        'score': 'Top',
        'leaderboard': 'Topka',
        'user': 'Użytkownik',
        'userMuted': 'Użytkownik %user% został wyciszony.',
        'userUnmuted': 'Wyłączono wyciszenie użytkownika %user%.',
        'mute': 'Wycisz',
        'unmute': 'Wyłącz wyciszenie',
        'mutedUsers': 'Wyciszeni użytkownicy',
        'activeUsers': 'Aktywni użytkownicy',
        'showActiveUsers': 'Pokaż aktywnych użytkowników',
        'none': 'Brak',
        'sounds': 'Dźwięki',
        'page_back_button': 'Wróć',
        'page_create_party': 'Stwórz party',
        'page_join_party': 'Dołącz',
        'page_login_and_play': 'Zaloguj',
        'page_logout': 'Wyloguj',
        'page_menu_login_facebook': 'Zaloguj z Facebook',
        'page_menu_login_google': 'Zaloguj z Google',
        'page_menu_main_free_coins': 'Darmowe Monety',
        'page_menu_main_gifts': 'Prezenty',
        'page_menu_main_dailyquests': 'Zadania',
        'page_party_join_error': 'Nie można dołączyć do tego party. Upewnij się, że token jest prawidłowy lub stwórz nowy.',
        'page_play': 'Graj',
        'page_play_as_guest': 'Graj jako gość',
        'page_shop': 'Sklep',
        'page_spectate': 'Obserwuj',
        'page_stats': 'Statystyki'
    },
    'en': {
        'start': 'Home',
        'settings': 'Settings',
        'restoreSettings': 'Restore default settings',
        'animationGroup': 'Animation',
        'zoomGroup': 'Zoom',
        'respGroup': 'Respawn',
        'namesGroup': 'Names',
        'massGroup': 'Mass',
        'skinsGroup': 'Skins',
        'foodGroup': 'Food',
        'transparencyGroup': 'Transparency / colors',
        'gridGroup': 'Grid / sectors',
        'miniMapGroup': 'Minimap',
        'helpersGroup': 'Helpers',
        'mouseGroup': 'Mouse control',
        'hudGroup': 'HUD',
        'chatGroup': 'Chat',
        'statsGroup': 'Stats',
        'extrasGroup': 'Extras',
        'noSkins': 'No skins',
        'noNames': 'No names',
        'noColors': 'No colors',
        'showMass': 'Show mass',
        'skipStats': 'Skip stats after death',
        'showQuest': 'Show quest',
        'autoZoom': 'Auto zoom',
        'animation': 'Animation delay',
        'suckAnimation': 'Cell Eat [Sucking] Animation',
        'virusGlow': 'Virus Glow',
        'borderGlow': 'Border Glow',
        'zoomSpeedValue2': 'Zoom speed',
        'quickResp': 'Quick respawn (hotkey)',
        'autoResp': 'Auto respawn',
        'autoHideCellsInfo': 'Auto hide names and mass',
        'autoHideNames': 'Auto hide names',
        'autoHideMass': 'Auto hide mass',
        'autoHideFood': 'Auto hide food - mass',
        'autoHideFoodOnZoom': 'Auto hide food - zoom',
        'optimizedNames': 'Optimized names',
        'hideMyName': 'Hide my name',
        'hideTeammatesNames': 'Hide teammates names',
        'optimizedMass': 'Optimized mass (+/-2%) & Merge timer BETA off\r\n Suggested to be enabled for Lag reduce',
        'shortMass': 'Short mass (k)',
        'virMassShots': 'Virus shots',
        'hideMyMass': 'Hide my mass',
        'hideEnemiesMass': 'Hide enemies mass',
        'vanillaSkins': 'Vanilla skins',
        'customSkins': 'Custom skins',
        'videoSkins': 'Video skins (.mp4 .webm .ogv)',
        'videoSkinsMusic': 'Sound from other\'s Video skins when both C3',
        'myTransparentSkin': 'My transparent skin',
        'myCustomColor': 'My custom color',
        'transparentCells': 'Transparent cells',
        'transparentViruses': 'Transparent viruses',
        'transparentSkins': 'Transparent skins',
        'showGrid': 'Show grid',
        'showBgSectors': 'Show background sectors',
        'showMapBorders': 'Show map borders',
        'showGhostCells': 'Ghost cells (fps drop)',
        'showGhostCellsInfo': 'Ghost cells info (confusing)',
        'showMiniMap': 'Show minimap',
        'showMiniMapGrid': 'Show minimap grid',
        'showMiniMapGuides': 'Show minimap guides',
        'showExtraMiniMapGuides': 'Show extra minimap guides',
        'showMiniMapGhostCells': 'Show ghost cells',
        'oneColoredTeammates': 'One-colored teammates',
        'optimizedFood': 'Optimized food',
        'rainbowFood': 'Rainbow food',
        'oppColors': 'Opponents colors',
        'oppRings': 'Opponents rings',
        'virColors': 'Viruses colors',
        'splitRange': 'Split range',
        'qdsplitRange': 'Quick double split range', //Sonia2
        'sdsplitRange': 'Slow double split range', //Sonia2
        'virusesRange': 'Viruses range',
        'textStroke': 'Names and mass stroke',
        'namesStroke': 'Names stroke',
        'massStroke': 'Mass stroke',
        'cursorTracking': 'Cursor tracking',
        'teammatesInd': 'Teammates indicators',
        'mouseSplit': 'LMB - Mouse split',
        'mouseFeed': 'RMB - Mouse feed',
        'mouseInvert': 'Invert mouse buttons',
        'disableChat': 'Disable chat',
        'hideChat': 'Hide chat',
        'chatSounds': 'Sound notifications',
        'chatEmoticons': 'Emoticons',
        'showChatImages': 'Show images on chat',
        'showChatVideos': 'Show videos on chat',
        'showChatBox': 'Chatbox instead of popups',
        'messageSound': 'Message notification sound',
        'commandSound': 'Command notification sound',
        'virusSoundurl': 'Virus shot sound',
        'virusSound': 'Virus shot sound',
        'jellyPhisycs': 'Jelly physics',
        'showTop5': 'Show teamboard',
        'showTargeting': 'Show targeting',
        'showTime': 'Show current time',
        'showLbData': 'Show leaderboard mass',
        'normalLb': '\"Leaderboard\" header',
        'centeredLb': 'Centered leaderboard',
        'fpsAtTop': 'Game stats at the top',
        'showStats': 'Show game stats',
        'showStatsMass': 'Game stats: Mass',
        'showStatsESTE': 'Game stats: Enemy\'s STE',
        'showStatsEMTE': 'Game stats: Enemy\'s MTE',
        'showStatsMTE': 'Game stats: Our MTE',
        'showStatsSTE': 'Game stats: Our STE',
        'showStatsTTE': 'Game stats: Minimal tricksplit teammate\'s mass',
        'showStatsPTE': 'Game stats: Maximal enemy\'s mass for presplit',
        'showStatsN16': 'Game stats: n/16',
        'showStatsFPS': 'Game stats: FPS',
        'blockPopups': 'Block popups (ads/shop/quest)',
        'hotkeys': 'Hotkeys',
        'hk-inst-assign': 'To assign a hotkey click on the input field and press your chosen key.',
        'hk-inst-delete': 'To delete a hotkey click on the input field and press the DELETE key.',
        'hk-inst-keys': 'Possible key combinations with the CTRL and ALT keys.',
        'hk-bots-split': 'Bots split',
        'hk-bots-feed': 'Bots feed',
        'hk-bots-ai': 'Bots AI toggle',
        'hk-feed': 'Feed',
        'hk-macroFeed': 'Macro feed',
        'hk-split': 'Split',
        'hk-doubleSplit': 'Double split',
        'hk-split16': 'Split 16',
        'hk-pause': 'Cell pause',
        'hk-showTop5': 'Show/hide teamboard',
        'hk-showTime': 'Show/hide current time',
        'hk-showSplitRange': 'Show/hide split range',
        'hk-showSplitInd': 'Show/hide split indicators',
        'hk-showTeammatesInd': 'Show/hide teammates indicators',
        'hk-showOppColors': 'Show/hide opponents colors',
        'hk-toggleSkins': 'Toggle skins (custom/default)',
        'hk-showSkins': 'Show/hide skins',
        'hk-transparentSkins': 'Toggle transparent skins',
        'hk-showStats': 'Show/hide game stats',
        'hk-toggleCells': 'Toggle own cells (smallest/biggest)',
        'hk-showFood': 'Show/hide food',
        'hk-showGrid': 'Show/hide grid',
        'hk-showMiniMapGuides': 'Show/hide minimap guides',
        'hk-hideChat': 'Show/hide chat',
        'hk-showHUD': 'Show/hide HUD',
        'hk-copyLb': 'Copy leaderboard',
        'hk-showLb': 'Show/hide leaderboard',
        'hk-toggleAutoZoom': 'Toggle auto zoom',
        'hk-resetZoom': 'Reset zoom',
        'hk-zoomLevel': 'Zoom level',
        'hk-toggleDeath': 'Toggle death location',
        'hk-clearChat': 'Show chat history / Clear chat',
        'hk-showBgSectors': 'Show/hide background sectors',
        'hk-hideBots': 'Show/hide small bots',
        'hk-showNames': 'Show/hide names',
        'hk-hideTeammatesNames': 'Show/hide teammates names',
        'hk-showMass': 'Show/hide mass',
        'hk-showMiniMap': 'Show/hide minimap',
        'hk-chatMessage': 'Enter chat message',
        'hk-quickResp': 'Quick respawn',
        'hk-autoResp': 'Toggle auto respawn',
        'hk-switchServerMode': 'Switch server [public/private]',
        'hk-showTargeting': 'Show/hide targeting panel',
        'hk-voiceChat': 'Voice to text',
        'hk-GhostCellsInfo': ' Show ghost cells information',
        'hk-Autoplay': 'Auto Play',
        'hk-setTargeting': 'Start/stop targeting (following)',
        'hk-cancelTargeting': 'Cancel targeting',
        'hk-changeTarget': 'Change target',
        'hk-privateMiniMap': 'Show target on the minimap',
        'hk-showQuest': 'Show/hide quest',
        'commands': 'Commands',
        'comm1': 'Feed me!',
        'comm2': 'Split into me!',
        'comm3': 'Need backup at %currentSector%!',
        'comm4': 'Enemy spotted at %currentSector%!',
        'comm5': 'Need a teammate!',
        'comm6': 'Tank the virus!',
        'comm7': 'Eat the virus!',
        'comm8': 'Let\'s bait!',
        'comm9': 'Fake tricksplit!',
        'comm0': 'Fuck!',
        'comm10': 'Tricksplit!',
        'comm11': 'Left!',
        'comm12': 'Up!',
        'comm13': 'Right!',
        'comm14': 'Bottom!',
        'comm15': 'Fake Tricksplit',
        'comm16': 'Popsplit',
        'comm17': 'Double Popsplit',
        'comm18': 'Reversed Tricksplit',
        'comm19': 'Canonsplit',
        'comm20': 'Reversed Canonsplit',
        'comm21': 'Bowlingsplit',
        'comm22': 'Auto feed trick',
        'comm23': 'Pause',
        'comm24': 'ANTI alarm stage 1',
        'comm25': 'ANTI alarm stage 2',
        'comm26': 'ANTI alarm stage 3',
        'comm27': 'ANTI alarm stage 4',
        'comm28': 'ANTI alarm stage 5',
        'comm29': 'Presplit',
        'comm30': 'Party Run tricks',
        'saveComm': 'Save commands',
        'theme': 'Theme',
        'restoreThemeSettings': 'Restore theme default settings',
        'basicTheming': 'Basic theming',
        'themePreset': 'Theme preset',
        'themeType': 'Theme type',
        'darkTheme': 'Dark theme',
        'lightTheme': 'Light theme',
        'mainColor': 'Main color',
        'bgColor': 'Background',
        'bordersColor': 'Map borders',
        'gridColor': 'Grid',
        'sectorsColor': 'Sectors font',
        'namesColor': 'Names',
        'namesStrokeColor': 'Names stroke',
        'massColor': 'Mass',
        'massStrokeColor': 'Mass stroke',
        'virusColor': 'Virus',
        'virusStrokeColor': 'Virus stroke',
        'virusGlowColor': "Virus Glow",
        "borderGlowColor": "Border Glow",
        'mVirusColor': 'Mothercell',
        'mVirusStrokeColor': 'Mothercell stroke',
        'virusGlowSize': 'Virus Glow Size',
        'borderGlowSize': 'Border Glow Size',
        'foodColor': 'Food',
        'namesFont': 'Names font',
        'massFont': 'Mass font',
        'sectorsFont': 'Sectors font',
        'namesScale': 'Names scale',
        'massScale': 'Mass scale',
        'virMassScale': 'Virus mass scale',
        'strokeScale': 'Text stroke scale',
        'foodSize': 'Food size',
        'bordersWidth': 'Map borders width',
        'sectorsWidth': 'Sectors grid width',
        'sectorsFontSize': 'Sectors font size',
        'cellsAlpha': 'Cells transparency',
        'skinsAlpha': 'Skins transparency',
        'virusAlpha': 'Virus transparency',
        'textAlpha': 'Names & mass transparency',
        'virusStrokeSize': 'Virus stroke size',
        "virusGlowSize": "Virus Glow Size",
        'teammatesIndColor': 'Teammate indicator',
        'cursorTrackingColor': 'Cursor tracking',
        'splitRangeColor': 'Split range',
        'enemyBSTEDColor': 'B2STE Enemy Color', //Sonia2
        'enemyBSTEColor': 'BSTE Enemy Color', //Sonia2
        'enemyBColor': 'Bigger Enemy Color', //Sonia2
        'enemySColor': 'Smaller Enemy Color', //Sonia2
        'enemySSTEColor': 'SSTE Enemy Color', //Sonia2
        'enemySSTEDColor': 'S2STE Enemy Color', //Sonia2
        'safeAreaColor': 'Safe area',
        'dangerAreaColor': 'Danger area',
        'ghostCellsColor': 'Ghost cells',
        'ghostCellsAlpha': 'Ghost cells transparency',
        'menuTheming': 'Menu',
        'menuPreset': 'Menu theme',
        'menuMainColor': 'Main color',
        'menuBtnTextColor': 'Button text',
        'menuPanelColor': 'Panel',
        'menuPanelColor2': 'Panel (2)',
        'menuTextColor': 'Panel text',
        'menuTextColor2': 'Panel text (2)',
        'btn1Color': 'Button #1',
        'btn1Color2': 'Button #1 (2)',
        'btn2Color': 'Button #2',
        'btn2Color2': 'Button #2 (2)',
        'btn3Color': 'Button #3',
        'btn3Color2': 'Button #3 (2)',
        'btn4Color': 'Button #4',
        'btn4Color2': 'Button #4 (2)',
        'menuBg': 'Panel background image',
        'menuOpacity': 'Transparency',
        'hudTheming': 'HUD',
        'hudMainColor': 'Main color',
        'hudColor': 'Background',
        'hudTextColor': 'Text',
        'statsHudColor': 'Stats',
        'timeHudColor': 'Time',
        'top5MassColor': 'Mass',
        'lbMeColor': 'Leaderboard - me',
        'lbTeammateColor': 'Leaderboard - teammate',
        'hudFont': 'HUD font',
        'hudScale': 'HUD scale',
        'chatTheming': 'Chat',
        'messageColor': 'Message background',
        'messageTextColor': 'Message text',
        'messageTimeColor': 'Message time',
        'messageNickColor': 'Message nick',
        'commandsColor': 'Command background',
        'commandsTextColor': 'Command text',
        'commandsTimeColor': 'Command time',
        'commandsNickColor': 'Command nick',
        'chatBoxColor': 'Chatbox color',
        'chatScale': 'Chat scale',
        'miniMapTheming': 'Minimap',
        'miniMapSectorsColor': 'Sectors',
        'miniMapSectorColor': 'Current sector',
        'miniMapGuidesColor': 'Guides',
        'miniMapNickColor': 'Nick',
        'miniMapNickStrokeColor': 'Nick stroke',
        'miniMapMyCellColor': 'My cell',
        'miniMapMyCellStrokeColor': 'My cell stroke',
        'miniMapTeammatesColor': 'Teammates',
        'miniMapDeathLocationColor': 'Death location',
        'miniMapFont': 'Minimap font',
        'miniMapNickFont': 'Nick font',
        'miniMapWidth': 'Minimap width',
        'miniMapSectorsOpacity': 'Sectors transparency',
        'miniMapNickSize': 'Nick size',
        'miniMapNickStrokeSize': 'Nick stroke size',
        'miniMapMyCellSize': 'My cell size',
        'miniMapMyCellStrokeSize': 'My cell stroke size',
        'miniMapTeammatesSize': 'Teammates size',
        'miniMapGhostCellsColor': 'Ghost cells',
        'miniMapGhostCellsAlpha': 'Ghost cells transparency',
        'imagesTheming': 'Graphics / cursors',
        'customBackground': 'Custom background image',
        'customCursor': 'Custom cursor image',
        'hideChatMsgA': 'Chat is visible!',
        'hideChatMsgB': 'Chat is hidden!',
        'showSkinsMsgA': 'Skins are visible!',
        'showSkinsMsgB': 'Skins are hidden!',
        'hideSmallBotsMsgA': 'Small bots are visible!',
        'hideSmallBotsMsgB': 'Small bots are hidden!',
        'autoRespMsgA': 'Auto respawn is on!',
        'autoRespMsgB': 'Auto respawn is off!',
        'autoZoomMsgA': 'Auto zoom is on!',
        'autoZoomMsgB': 'Auto zoom is off!',
        'targetNotSet': '',
        'targetDead': 'Dead',
        'targetDistance': 'Distance',
        'targetMass': 'Total Mass',
        'totalPartyPlayers': '',
        'totalPartyMass': '',
        'exportImport': 'Export / import settings',
        'exportSettings': 'Export settings',
        'exportInfo': 'To export selected settings copy the code below and save it to a text file encoded in Unicode.',
        'importSettings': 'Import settings',
        'importInfo': 'To import selected settings paste an exported code below and press the \"Import settings\" button.',
        'profile': 'Profile',
        'profiles': 'Profiles',
        'skins': 'Skins',
        'moreSkins': 'Add skins',
        'thanks': 'Thanks to Awesome!',
        'saveSett': 'Save settings',
        'saved': 'Saved!',
        'resetSett': 'Reset to default',
        'close': 'Close',
        'enterChatMsg': 'Enter chat message',
        'activeParties': 'Active parties',
        'noActiveParties': 'No active parties ;(',
        'playlist': 'Playlist',
        'pause': 'PAUSE!',
        'visit': 'Visit',
        'exit': 'Legend mod Express: Are you sure you want to quit the game?',
        'blockWarn': 'WARNING! Popups are blocked in the settings.',
        'unblockPopups': 'Temporary unblock',
        'mass': 'Mass',
        'score': 'Score',
        'leaderboard': 'Leaderboard',
        'user': 'User',
        'userMuted': 'User %user% has been muted.',
        'userUnmuted': 'User %user% has been unmuted.',
        'mute': 'Mute',
        'unmute': 'Unmute',
        'mutedUsers': 'Muted users',
        'activeUsers': 'Active users',
        'showActiveUsers': 'Show active users',
        'none': 'None',
        'sounds': 'Sounds',
        'page_menu_main_free_coins': 'Free Coins',
        'page_menu_main_gifts': 'Gifts',
        'page_menu_main_dailyquests': 'Daily Quest',
        'page_shop': 'Shop'
    }
}